### ISSUE TITLE
Configuration via environment variables

### ISSUE THREAD

**Issue by LoicGombeaud** [deeplay-io/verdaccio-openid-connect#13]
Hi again!

Is it possible to configure the plugin via environment variables, instead of via `config.yaml`?

We're using verdaccio deployed on a Kubernetes cluster (with the helm chart), and the only way that I found to set the `clientSecret` is in the `ConfigMap`, which is unsafe.

If we could set it via an environment variable, then it would be possible to set it in a secret and then inject it in the container.

I'm not sure I'm making myself clear, but basically what I'd like to see is a `VERDACCIO_OPENID_CLIENT_SECRET` variable, is it currently possible?

**Comment by aikoven** [comment]
Hey, sorry for not answering for so long.

This can be done outside of this plugin:

1. Put the config in a `ConfigMap` with variables instead of actual secrets, like

   ```yaml
   clientSecret: $VERDACCIO_OPENID_CLIENT_SECRET
   ```
2. Deploy Verdaccio with `initContainer` or a custom entrypoint that performs a variable substitution in that config before passing it to Verdaccio. This can be done with [envsubst](https://www.gnu.org/software/gettext/manual/html_node/envsubst-Invocation.html) GNU program or a [string-env-interpolation](https://www.npmjs.com/package/string-env-interpolation) NPM package.

This might look cumbersome, but I see it as a flexible and universal approach.

Otherwise, we could add env var support for this exact value (client secret) to the plugin. PRs are welcome!
